name: Districts Autoupdate
on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * TUE'

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: Andrew-Chen-Wang/district-autoupdate@v1.0.1
      with:
        districts-repo: 'Andrew-Chen-Wang/districts'
        tag-branch: 'non-voting-geojson-update'
        path: ${{ github.workspace }}/districts.geojson
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Autoupdate districts
        commit_author: GitHub Actions <actions@github.com>
