name: Single File Autoupdates

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * TUE'

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Dependencies
      run: |
        pip install --upgrade pip wheel
        pip install -r requirements/single-file-autoupdate.txt
    - name: Grab current legislators
      run: python bin/current_legislators.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Autoupdate legislators
        commit_author: GitHub Actions <actions@github.com>
